### ISSUE TITLE
New install not working right

### ISSUE THREAD

**Issue by TekExplorer** [NamelessMC/Nameless-Docker#2]
i have been attempting to install nameless in my server for a bit. i got it acessable behind traefik and went ahead with the install... [/install.php?step=database] database... friendly urls... then the dang thing sends me to the upgrade from v1 page! [/install.php?step=upgrade] what the actual hekk

**Comment by Derkades** [comment]
Did you enable friendly URLs? Try it with friendly URLs disabled first

**Comment by TekExplorer** [comment]
I did! There is very few options I could change in the web installer... It does the same if I select upgrade too...

**Comment by Sabinno** [comment]
Having this exact same issue. I wanted to start fresh with a new install; I have erased all data from bind mounts, pruned all docker networks, volumes, containers, and images to no avail. Afaik there's no data whatsoever that this could be storing somewhere to determine upgrade eligibility that it didn't detect on the first install, when everything worked properly. Upon each reinstall, I used a different browser with Private Mode to ensure cache and cookies were not causing issues; same results. It is now no longer possible to install NamelessMC with docker on my machine.

What determines upgrade eligibility?

**Comment by Derkades** [comment]
I can also reproduce this. First install works fine, this issue appears for any future installs.

> What determines upgrade eligibility?

@samerton ?

**Comment by Derkades** [comment]
MariaDB has a sneaky VOLUME declaration in its [Dockerfile](https://github.com/docker-library/mariadb/blob/master/10.5/Dockerfile#L117) so keep in mind that even if you didn't create a volume yourself it'll still persist the data.     

However, even when testing using `docker-compose down; docker volume prune -f, sudo rm -rf /path/to/data` it still won't work. Weirdly enough, while testing this over 10 times, it worked randomly one time! I don't understand why

**Comment by Derkades** [comment]
Xemah has written a new installer for v2-pre8. This is not released yet, but I've created a new tag for v2 development builds. If you have time, please try `namelessmc/php:dev`. (testing only!)

**Comment by Derkades** [comment]
Nevermind, figured it out. The installer deletes the /tmp directory, and php uses the /tmp directory for saving sessions.

**Comment by Derkades** [comment]
Yes, confirmed working now. Enjoy!

**Comment by TekExplorer** [comment]
Good to know! Which image should I be using?

**Comment by Derkades** [comment]
:dev for testing, :latest for production. Currently latest is v2-pre7 and dev is the v2 branch
