### ISSUE TITLE
Email error when forgot password is triggered

### ISSUE THREAD

**Issue by Magnum97** [NamelessMC/Nameless-Docker#4]
I was testing the mail sending but I did not receive anything. I logged in to get this message from the website
count(): Parameter must be an array or an object that implements Countable

I also checked the nameless-php container logs and learned that sendmail was not found
```
sh: 1: /usr/sbin/sendmail: not found
172.28.0.6 -  30/Jan/2021:05:05:38 +0000 "POST /index.php" 200

```

**Comment by Derkades** [comment]
> count(): Parameter must be an array or an object that implements Countable

This is a PHP8 issue, please use the PHP 7.4 images instead.

> sh: 1: /usr/sbin/sendmail: not found

I'll include sendmail in the image

**Comment by Derkades** [comment]
Images deployed, enjoy
