### ISSUE TITLE
/data is not owned by the correct user, we are uid 33

### ISSUE THREAD

**Issue by i9nite** [NamelessMC/Nameless-Docker#6]
I am trying to install namelessmc with docker-compose but it's giving me this errors :(
![pic-full-220330-0022-00](https://user-images.githubusercontent.com/97473978/160716864-2a602568-2814-48f1-be41-fb9ef7d3b916.png)

```
Creating namelessmc_db_1 ... done
Creating namelessmc_php_1 ... done
Creating namelessmc_nginx_1 ... done
Attaching to namelessmc_db_1, namelessmc_php_1, namelessmc_nginx_1
db_1     | 2022-03-29 22:21:50+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.7.3+maria~focal started.
php_1    | /data is not owned by the correct user, we are uid 33
db_1     | 2022-03-29 22:21:50+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
nginx_1  | /data is not owned by the correct user, we are uid 33
db_1     | 2022-03-29 22:21:50+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.7.3+maria~focal started.
db_1     | 2022-03-29 22:21:50+00:00 [Note] [Entrypoint]: MariaDB upgrade not required
db_1     | 2022-03-29 22:21:50 0 [Note] mariadbd (server 10.7.3-MariaDB-1:10.7.3+maria~focal) starting as process 1 ...
db_1     | 2022-03-29 22:21:50 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1     | 2022-03-29 22:21:50 0 [Note] InnoDB: Using transactional memory
db_1     | 2022-03-29 22:21:50 0 [Note] InnoDB: Number of transaction pools: 1
namelessmc_php_1 exited with code 1
db_1     | 2022-03-29 22:21:50 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
db_1     | 2022-03-29 22:21:50 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
db_1     | 2022-03-29 22:21:50 0 [Note] InnoDB: Using Linux native AIO
db_1     | 2022-03-29 22:21:50 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
db_1     | 2022-03-29 22:21:50 0 [Note] InnoDB: Completed initialization of buffer pool
db_1     | 2022-03-29 22:21:50 0 [Note] InnoDB: 128 rollback segments are active.
db_1     | 2022-03-29 22:21:50 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1     | 2022-03-29 22:21:50 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1     | 2022-03-29 22:21:50 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1     | 2022-03-29 22:21:50 0 [Note] InnoDB: 10.7.3 started; log sequence number 42579; transaction id 14
db_1     | 2022-03-29 22:21:50 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1     | 2022-03-29 22:21:50 0 [Note] Plugin 'FEEDBACK' is disabled.
db_1     | 2022-03-29 22:21:50 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
db_1     | 2022-03-29 22:21:50 0 [Note] InnoDB: Buffer pool(s) load completed at 220329 22:21:50
db_1     | 2022-03-29 22:21:50 0 [Note] Server socket created on IP: '0.0.0.0'.
db_1     | 2022-03-29 22:21:50 0 [Note] Server socket created on IP: '::'.
db_1     | 2022-03-29 22:21:50 0 [Note] mariadbd: ready for connections.
db_1     | Version: '10.7.3-MariaDB-1:10.7.3+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
namelessmc_nginx_1 exited with code 1

```

**Comment by Derkades** [comment]
Run `chown -R 33:33 /path/to/volume` on the host where /path/to/volume is the host directory you mounted in /data. Or, if you want to use a different user, change the `user` option in docker-compose.yml

Updated the readme to explain this better: https://github.com/NamelessMC/Nameless-Docker/commit/6aebf28ef9e90f2f9b1cbfc2a7a5db28f0a2e58c

**Comment by i9nite** [comment]
thanks @Derkades , that did fix that issue but now there is a new one.
everything looks like it's working fine but when go to the website "ip:8080/install.php" (the default port that in the docker copose file is 8080 but it in the container it was 80, it was easy fix, just good to know I guess ) the website is just keep on loading for like 5 min and then it load like this
![pic-window-220330-2152-49](https://user-images.githubusercontent.com/97473978/160919485-81cc2a8f-11d6-4d6e-a158-9ba99ed4e91a.png)
there is only some errors in the php container

```
Data directory contains files, not downloading NamelessMC
 
 [30-Mar-2022 19:46:07] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
 
 [30-Mar-2022 19:46:07] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
 
 [30-Mar-2022 19:46:07] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
 
 [30-Mar-2022 19:46:07] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
 
 [30-Mar-2022 19:46:07] NOTICE: fpm is running, pid 1
 
 [30-Mar-2022 19:46:07] NOTICE: ready to handle connections
 
 172.29.0.4 -  30/Mar/2022:19:46:58 +0000 "GET /index.php" 200

 172.29.0.4 -  30/Mar/2022:19:46:58 +0000 "GET /install.php" 200

 172.29.0.4 -  30/Mar/2022:19:52:21 +0000 "GET /index.php" 200
```

**Comment by Derkades** [comment]
can you open developer tools (F12), refresh the page and take a screenshot of the console and network tabs?

**Comment by i9nite** [comment]
yes.
![pic-window-220330-2252-47](https://user-images.githubusercontent.com/97473978/160928915-a33a3ad3-e093-4ad7-bd3b-5f5b332b96fc.png)
the console is empty
![pic-window-220330-2253-18](https://user-images.githubusercontent.com/97473978/160929018-0d07ed7f-4fcb-4e98-8f7b-8ffcb2b7cca4.png)

**Comment by i9nite** [comment]
after 5 minutes something showed in the console

![pic-window-220330-2256-22](https://user-images.githubusercontent.com/97473978/160929474-262aa196-87dc-41e8-85b3-95641034fdc5.png)

you can check it out for yourself if you feel like it, the ip is accessable

**Comment by i9nite** [comment]
I got some extra errors 
![pic-full-220401-0525-10](https://user-images.githubusercontent.com/97473978/161189468-1fe7ef4a-d592-47ac-9691-98452b4b9acb.png)

**Comment by Derkades** [comment]
Did you fix it? When I go to the IP address, it works perfectly fine for me (load time 900ms)

~~The javascript syntax error makes it sound like QtWebEngine is not able to render the page, did you try a different browser?~~

Works in falkon and firefox:
![image](https://user-images.githubusercontent.com/15892014/161230619-8922a6c8-358b-4603-8add-239b7afc4df4.png)

**Comment by i9nite** [comment]
no I didn't do anything, and it's taking a really long time to load, maybe it's an error from my end I will see if my friends have the same problem

**Comment by i9nite** [comment]
A friend of main have no problemes what so ever, do you have anti vpn/proxy protication for the site by default?
I turned off the vpn and It worked just fine, how can I disable the anti proxy/vpn thingy? and thank you for the help

**Comment by i9nite** [comment]
ok, So as you know the website wasn't loading for me and then I thought that it was my vpn, so I thought I will put nameless mc behind the nginx proxy and give it a ssl cert, so after doing that, the website works fine even with my vpn on and now I am very confused.

thanks for the help

**Comment by Derkades** [comment]
That almost sounds like your VPN is actively interfering with non-encrypted traffic (MITM attack).

**Comment by i9nite** [comment]
yaa I do block p2p and some other ips from my vpn, maybe that's the problem :)
