### ISSUE TITLE
Failed to connect to the database: SQLSTATE[HY000] [1130] Host '172.18.0.3' is not allowed to connect to this MariaDB server

### ISSUE THREAD

**Issue by CallMeYuuuu** [NamelessMC/Nameless-Docker#7]
All the credentials are correct and when I try to connect to the DB in the installation process I just get that error:
`Failed to connect to the database: SQLSTATE[HY000] [1130] Host '172.18.0.1' is not allowed to connect to this MariaD` 
172.18.0.3 is the PHP container

DB Container log: `2022-09-15` 17:43:33 5 [Warning] Aborted connection 5 to db: 'unconnected' user: 'unauthenticated' host: '172.18.0.1' (This connection closed normally without authentication)` 172.18.0.1 is the namelessmc network gateway

Please help

**Comment by Derkades** [comment]
It seems like you have configured MariaDB to only accept connections from specific hosts. Are you using the default user and database created by the MariaDB container using environment variables?

**Comment by CallMeYuuuu** [comment]
Fixed it!

You have to change MYSQL in Docker compose to MARIADB like this

MYSQL_ROOT_PASSWORD: nameless
MYSQL_USER: nameless
MYSQL_PASSWORD: nameless
MYSQL_DATABASE: nameless

to this

MARIADB_ROOT_PASSWORD: nameless
MARIADB_USER: nameless
MARIADB_PASSWORD: nameless
MARIADB_DATABASE: nameless

**Comment by Derkades** [comment]
I didn't know about the `MARIADB_` variables. Apparently they were introduced with version 10.6, according to the docker hub page. It says `MYSQL_` variables still work though, so I guess initialization failed for some other reason. I will update the docker compose file to use `MARIADB_` variables.
