### ISSUE TITLE
Invalid mount config for type "bind": bind source path does not exist: /data/compose/37/db

### ISSUE THREAD

**Issue by sircurse** [NamelessMC/Nameless-Docker#8]
Hi there,

I m trying to install using the compose on portainer, when I execute to deploy it I got the following message error:

`Deployment error
failed to deploy a stack: Container namelessmc-db-1 Creating Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /data/compose/39/db`

This the compose part of the DB:
`  db:
    image: mariadb
    volumes:
      - type: bind
        source: ./db
        target: /var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: nameless
      MARIADB_USER: nameless
      MARIADB_PASSWORD: nameless
      MARIADB_DATABASE: nameless
    restart: unless-stopped  `

Any idea on how to mange it?
Thank you,
Curse.

**Comment by Derkades** [comment]
Create the directory that the error message says doesn't exist
